import AnimatedText from '@/components/AnimatedText'
import React from 'react'
import Head from 'next/head'
import Layout from '@/components/Layout'
import Image from 'next/image'
import profilePic from '../../public/images/profile/developer-pic-2.jpg'
import Skills from '@/components/Skills'
import Experience from '@/components/Experience'
import Education from '@/components/Education'
import TransitionEffect from '@/components/TransitionEffect'
const about = () => {
    return (
        <>
            <Head>
                <title>JA | About Page</title>
                <meta name="My Profile" content="Generated by JA" />
            </Head>
            <TransitionEffect />
            <main className='flex w-full flex-col items-center justify-center dark:text-primaryDark'>
                <Layout className='pt-16'>
                    <AnimatedText text="Innovative Code Craftsman" className='mb-16 lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:mb-8' />
                    <div className='grid w-full grid-cols-8 gap-16 sm:gap-8'>
                        <div className='col-span-3 flex flex-col items-start justify-start xl:col-span-4 md:order-2 md:col-span-8'>
                            <h2 className='mb-4 text-lg font-bold uppercase text-dark/75 dark:text-primaryDark/75'>About Me</h2>
                            <p className='font-medium '>
                                Hello, my name is John Alexis Abres. I am a highly talented and motivated programmer with a proven track record of success in technology and software development.
                                I demonstrated my remarkable potential in the Philippines National Skill Competition - TESDA 2022, earning a Gold Medal at the Provincial level and a Silver Medal at the Regional level.
                            </p>
                            <p className='my-4 font-medium '>
                                I am passionate about making ideas become reality, and I am constantly looking for opportunities to use my programming knowledge and creativity to solve hard problems.
                                My devotion to perfection and my desire to be at the cutting edge of technology lead me to design solutions that have a significant influence in the field of software development.
                            </p>
                            <p className='font-medium '>
                                I am excited to explore new possibilities, work on fascinating projects, and use my abilities to affect the future of software development and technological innovation.
                            </p>
                        </div>
                        <div className='col-span-3 relative h-max rounded-2xl border-2 border-solid border-dark
                        bg-light p-8 dark:bg-dark dark:border-primaryDark xl:col-span-4 md:order-1 md:col-span-8'>
                            <div className='absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-primaryDark' />
                            <Image src={profilePic} alt="John Alexis" className='w-full h-auto rounded-2xl'
                                priority
                                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                            />
                        </div>
                    </div>
                    <Skills />
                    <Experience />
                    <Education />
                </Layout>
            </main>
        </>
    )
}

export default about