import Layout from '@/components/Layout'
import Image from 'next/image';
import Head from 'next/head'
import profilePic from '../../public/images/profile/developer-pic-1.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import laptop from '../../public/images/svgs/computer-svgrepo-com.svg'
import TransitionEffect from '@/components/TransitionEffect';
export default function Home() {
  return (
    <>
      <Head>
        <title>JA | Home Page</title>
        <meta name="description" content="Generated by me" />
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-primaryDark'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col lg:text-center'>
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt="Profile" className='w-full h-auto lg:hidden md:inline-block md:w-full' 
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className='w-1/2 flex flex-col item-center self-center lg:w-full'>
              <AnimatedText text="Showcasing the Power of Code and Design in Making Ideas into Reality!" 
              className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl'/>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
                As a web developer, I am committed to transforming ideas into cutting-edge online apps. Explore my most recent projects, which demonstrate my experience in Next.js and web development.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/Resume.pdf" target={"_blank"}
                className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark
                dark:bg-primary dark:text-primaryDark hover:dark:bg-dark hover:dark:text-primaryDark hover:dark:border-primaryDark
                md:p-2 md:px-4 md:text-base'>
                Resume<LinkArrow className={'w-5 m-1'} />
                </Link>
                <Link href="mailto:abresjohnalexis@gmail.com" target={"_blank"}
                className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-primaryDark
                md:text-base'
                >Contact Me</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>
          <Image src={laptop} alt='Alexis' className='w-full h-auto'/>
        </div>
      </main>
    </>
  )
}
